Repository Recoded-Spark-Turkey-2022/Unboxed, pull requests merged in 2022-12, with the labels that each got.

#2 Build: addtion of Router +Testing Library. Setup of other Folders
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/App.test.js
  src/components/footer/Footer.jsx
  src/components/navbar/Navbar.jsx
  src/index.jsx
  src/logo.svg
  src/pages/homepage/Homepage.jsx
  src/pages/login/Login.jsx
  src/routers/Routers.js
  yarn.lock
Labels: Setup

#15 Setup Firebase
  .firebaserc
  database.rules.json
  firebase.json
  package-lock.json
  package.json
  src/firebaseFile.js
  src/pages/homepage/Homepage.jsx
  storage.rules
  yarn.lock
Labels: enhancement

#16 Nadim absi/issue12
  package-lock.json
  package.json
  src/components/google&facebook/Facebook.svg
  src/components/google&facebook/Google.svg
  src/components/google&facebook/LoginButtons.jsx
  src/components/google&facebook/LoginButtons.test.js
  src/components/loginForm/LoginForm.jsx
  src/components/loginForm/LoginForm.test.js
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.test.js
  src/index.css
  src/pages/login/Login.jsx
  src/pages/login/LoginImg.svg
  tailwind.config.js
  yarn.lock
Labels: enhancement, Design
